### ISSUE TITLE
Memes list missing

### ISSUE THREAD

**Issue by stalagmite7** [benoriol/memes_processing#1]
Hi, I was looking for an example to multimodal trainign and came across your repo (not sure if you have completed your work), but it seems to be missing a few image list files:

    Traceback (most recent call last):
      File "train.py", line 221, in <module>
    train_dataset = test.ImageTextMatcherDataLoader(TRAIN_METADATA_GOOD, TRAIN_METADATA_HATE, BASE_PATH, transform)
      File "/home/xxx/other_repos/memes_processing/module/test.py", line 213, in __init__
        love_paths = list(open(base_path + "/" + love_metadata))
    FileNotFoundError: [Errno 2] No such file or directory: 'data/train_data/redditMemesList.txt.train'

Could you please provide it so I can run the code? Thank you very much!

**Comment by benoriol** [comment]
The data is not published, in order to not spread hateful content. If you want to use the data for academic purposes, please contact me at benet.oriol.sabat@gmail.com
